name 'base_server'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures base_server'
long_description 'Installs/Configures base_server'
version '0.1.0'

depends 'zsh'
depends 'htop'
